# bundle exec jekyll serve --host=0.0.0.0

title: MycilaUtilities
description: Utils stuff for Arduino / ESP32 like Time, String functions, CircularBuffer, etc
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
